services:
  publisher:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./publisher/init-publisher.sh:/docker-entrypoint-initdb.d/init-publisher.sh
      - ./publisher/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./publisher/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./publisher/publisher-data:/var/lib/postgresql/data
    command: postgres -c config_file=/var/lib/postgresql/data/postgresql.conf

  subscriber1:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REPLICATOR_USER: ${REPLICATOR_USER}
      REPLICATOR_PASSWORD: ${REPLICATOR_PASSWORD}
    ports:
      - "5434:5432"
    depends_on:
      - publisher
    volumes:
      - ./subscriber-one/subscriber1_data:/var/lib/postgresql/data
      - ./subscriber-one/init-subscriber.sh:/docker-entrypoint-initdb.d/init-subscriber.sh
    entrypoint: ["/entrypoint.sh", "subdb1", "my_sub1"]

volumes:
  publisher_data:
  subscriber1_data: