services:
  publisher:
    image: postgres:15
    container_name: publisher
    ports:
      - "${PUBLISHER_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - ./publisher/init-publisher.sh:/docker-entrypoint-initdb.d/init-publisher.sh
      - ./publisher/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./publisher/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./publisher/publisher-data:/var/lib/postgresql/data
    command: postgres -c config_file=/var/lib/postgresql/data/postgresql.conf
    networks:
      - pgnet

  subscriber1:
    image: postgres:15
    container_name: subscriber1
    depends_on:
      - publisher
    ports:
      - "${SUBSCRIBER1_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REPLICATOR_USER: ${REPLICATOR_USER}
      REPLICATOR_PASSWORD: ${REPLICATOR_PASSWORD}
      PUBLISHER_HOST: publisher
    
    volumes:
      - ./subscriber-one/subscriber1_data:/var/lib/postgresql/data
      - ./subscriber-one/init-subscriber.sh:/init-subscriber.sh
    command: ["/bin/bash", "/init-subscriber.sh"]
    networks:
      - pgnet


networks:
  pgnet:
    driver: bridge