services:
  publisher:
    build:
      context: ./publisher
      dockerfile: Dockerfile.pub
    container_name: publisher
    hostname: publisher
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./publisher/publisher_data:/var/lib/postgresql/data
    command: postgres -c config_file=/var/lib/postgresql/data/postgresql.conf


  subscriber1:
    build:
      context: ./subscriber-one
      dockerfile: Dockerfile.sub
    container_name: subscriber1
    hostname: subscriber1
    depends_on:
      - publisher
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REPLICATOR_USER: ${REPLICATOR_USER}
      REPLICATOR_PASSWORD: ${REPLICATOR_PASSWORD}
      PUBLISHER_HOST: publisher
    volumes:
      - ./subscriber-one/subscriber_data:/var/lib/postgresql/data