services:
  postgres-master:
    image: postgres:15
    container_name: postgres-master
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
      - ./primary/init-master.sh:/docker-entrypoint-initdb.d/init-master.sh
      - ./primary/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./primary/master-data:/var/lib/postgresql/data
    command: postgres -c config_file=/var/lib/postgresql/data/postgresql.conf
    networks:
      - postgres-net

  
  postgres-replica:
    image: postgres:15
    container_name: postgres-replica
    depends_on:
      - postgres-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
      REPLICATOR_USER: replicator
      REPLICATOR_PASSWORD: '123456'
      MASTER_HOST: postgres-master
    ports:
      - "5434:5432"
    volumes:
      - ./replica/replica-data:/var/lib/postgresql/data
      - ./replica/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./replica/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./replica/init-replica.sh:/init-replica.sh
    command: ["/bin/bash", "/init-replica.sh"]
    networks:
      - postgres-net

volumes:
  master_data:
  replica_data:

networks:
  postgres-net:
    driver: bridge
