version: '3.8'

services:
    primary:
        image: postgres:15
        container_name: pg-primary
        ports:
            - "${PG_PRIMARY_PORT}:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./primary/postgres.conf:/etc/postgresql/postgresql.conf
        command: postgres -c config_file=/etc/postgresql/postgresql.conf
        networks:
            - pgnet
    

    replica1:
        image: postgres:15
        container_name: pg-replica1
        ports:
            - "${REPLICA1_PORT}:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        depends_on:
            - primary
        volumes:
            - ./replica1/postgres.conf:/etc/postgresql/postgresql.conf
        command: >
            bash -c "
                until pg_basebackup -h primary -D /var/lib/postgresql/data -U ${REPLICATION_USER} -W -Fp -Xs -P -R;
                do echo 'Waiting for primary...'; sleep 1; done &&
                postgres -c config_file=/etc/postgresql/postgresql.conf"
        networks:
            - pgnet
    
    replica2:
        image: postgres:15
        container_name: pg-replica2
        ports:
            - "${REPLICA2_PORT}:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        depends_on:
            - primary
        volumes:
            - ./replica/postgres.conf:/etc/postgresql/postgresql.conf
        command: >
            bash -c "
                until pg_basebackup -h primary -D /var/lib/postgresql/data -U ${REPLICATION_USER} -W -Fp -Xs -P -R;
                do echo 'Waiting for primary...'; sleep 1; done &&
                postgres -c config_file=/etc/postgresql/postgresql.conf"
        networks:
            - pgnet

networks:
  pgnet: