FROM postgres:15

COPY ./postgresql.conf /etc/postgresql/postgresql.conf

COPY ./init-replica.sh /usr/local/bin/init-replica.sh
RUN chmod +x /usr/local/bin/init-replica.sh

ENTRYPOINT ["/usr/local/bin/init-replica.sh"]
