services:
  primary:
    build:
      context: ./primary
      dockerfile: Dockerfile.primary
    container_name: primary
    hostname: primary
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./primary/primary_data:/var/lib/postgresql/data
    command: postgres -c config_file=/var/lib/postgresql/data/postgresql.conf


  replica1:
    build:
      context: ./replica-one
      dockerfile: Dockerfile.replica
    container_name: replica1
    hostname: replica1
    depends_on:
      - primary
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REPLICATOR_USER: ${REPLICATOR_USER}
      REPLICATOR_PASSWORD: ${REPLICATOR_PASSWORD}
      MASTER_HOST: primary
    volumes:
      - ./replica-one/replica_data:/var/lib/postgresql/data
    

  
  replica2:
    build:
      context: ./replica-two
      dockerfile: Dockerfile.replica
    container_name: replica2
    hostname: replica2
    depends_on:
      - primary
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REPLICATOR_USER: ${REPLICATOR_USER}
      REPLICATOR_PASSWORD: ${REPLICATOR_PASSWORD}
      MASTER_HOST: primary
    volumes:
      - ./replica-two/replica_data:/var/lib/postgresql/data
    
